version: 2.1

jobs:
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers

        steps:
            - checkout
            - restore_cache:
                keys:
                - dependencies-{{ checksum "package.json" }}

            - run:
                name: Install local dependencies
                command: npm install

            - save_cache:
                key: dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Building
                command: npm run build -- --prod
            
            - save_cache:
                key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist

    update_deployment_list:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        steps:
            - checkout
            - run:
                name: Deploy
                command: |
                    ./scripts/update_deploy_list.sh ./deployments.md
                    git add deployments.md
                    git commit --allow-empty -m "Update deployment list [ci skip]"  > /dev/null 2>&1
                    git push --force --quiet origin > /dev/null 2>&1

    deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:11.15-browsers
        parameters:
            version:
                type: string
                default: ""
        steps:
            - checkout
            - restore_cache:
                key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

            - run:
                name: Deploy
                command: |
                    mkdir gh-pages-branch
                    cd gh-pages-branch
                    git config --global user.name "CircleCI"
                    git init
                    echo adding remote
                    git remote add --fetch origin https://$GH_TOKEN@$github.com/torbjorv/angular-gh-pages.git > /dev/null 2>&1
                    echo checking out
                    git checkout gh-pages
                    echo running deployment
                    ./versions/deploy.sh << parameters.version >> ../dist https://torbjorv.github.io/angular-gh-pages/ $CIRCLE_COMPARE_URL $CIRCLE_BUILD_URL
                    cd ..
                    rm -rf gh-pages-branch
            
workflows:
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master

            # Deploy to gh-pages/builds/latest
            - deploy:
                name: deploy-dev
                requires:
                    - build
                filters:
                    branches:
                        only: master
                version: "$CIRCLE_BUILD_NUM"

            # Promoting a given build to 'prod' requires manual approval
            - approve:
                type: approval
                requires:
                    - build
                filters:
                    branches:
                        only: master

            # Deploys to gh-pages branch root level
            - deploy:
                name: deploy-prod
                requires:
                    - approve
                filters:
                    branches:
                        only: master
                version: "prod"                